clean_data:
  duplicated_method: "first"
validate_dataframe:
  duplicated_method: "first"
remove_outliers:
  feature_columns:
    response_column: "traffic_volume"
    month_column: "month"
    hour_column: "hour"
    day_of_week_column: "day_of_week"
    temperature_column: "temp"
    clouds_column: "clouds_all"
    weather_column: "weather_main"
    rain_column: "log_rain_1h"
  valid_values:
    temp_min: 233.1
    temp_max: 319.3
    log_rain_mm_min: 0
    log_rain_mm_max: 5.7
    clouds_min: 0
    clouds_max: 100
    hours_min: 0
    hours_max: 23
    month_min: 1
    month_max: 12
    response_min: 100
    response_max: 10000
    valid_weather:
      - "Clouds"
      - "Clear"
      - "Mist"
      - "Rain"
      - "Snow"
      - "Drizzle"
      - "Haze"
      - "Thunderstorm"
      - "Fog"
      - "Smoke"
      - "Squall"
    valid_week_days:
      - "Sunday"
      - "Monday"
      - "Tuesday"
      - "Wednesday"
      - "Thursday"
      - "Friday"
      - "Saturday"
generate_features:
  pipeline_and_app:
    log_transform_params:
      log_transform_column_names:
        - "rain_1h"
      log_transform_new_column_prefix: "log_"
    binarize_column_params:
      binarize_column_names:
        - "holiday"
      binarize_new_column_prefix: "binarize_"
      binarize_zero_value: "None"
    collapse_weather_categories_params:
      collapse_1:
        original_category: "Squall"
        to_category: "Thunderstorm"
      collapse_2:
        original_category: "Smoke"
        to_category: "Haze"
    one_hot_encoding_params:
      one_hot_encode_columns:
        - "weather_main"
        - "month"
        - "hour"
        - "day_of_week"
      drop: "first"
      sparse: False
  pipeline_only:
    drop_columns:
      - "snow_1h"
      - "weather_description"
      - "date_time"
    create_datetime_features_params:
      original_datetime_column: "date_time"
      month_column: "month"
      hour_column: "hour"
      day_of_week_column: "day_of_week"
    train_test_split_params:
      test_size: 0.2
      random_state: 24
      shuffle: True


model_training:
  random_forest:
    response_column: "traffic_volume"
    n_estimators: 50
    criterion: "squared_error"
    min_samples_split: 5
    max_features: "sqrt"
    oob_score: True
    n_jobs: -1
    random_state: 24

predict:
  response_column: "traffic_volume"

process_user_input:
  validate_user_input:
    column_names:
      - "holiday"
      - "month"
      - "hour"
      - "day_of_week"
      - "temp"
      - "clouds_all"
      - "weather_main"
      - "rain_1h"
    float_columns:
      - "temp"
      - "rain_1h"
      - "clouds_all"
      - "month"
      - "hour"